/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElBottom: typeof import('element-plus/es')['ElBottom']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
